<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Definition.fs" />
    <Compile Include="Library.fs" />
    <Compile Include="External.fs" />
    <Compile Include="Signature.fsi" />
    <Compile Include="Signature.fs" />
    <Compile Include="SignatureUsage.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Giraffe" Version="4.0.1" />
    <PackageReference Update="FSharp.Core" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GoToCSharp\GoToCSharp.csproj" />
  </ItemGroup>
</Project>
