// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsAutoComplete.Suave")>]
[<assembly: AssemblyProductAttribute("FsAutoComplete.Suave")>]
[<assembly: AssemblyDescriptionAttribute("A Suave web server for interfacing with FSharp.Compiler.Service over a HTTP.")>]
[<assembly: AssemblyVersionAttribute("0.30.2")>]
[<assembly: AssemblyFileVersionAttribute("0.30.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsAutoComplete.Suave"
    let [<Literal>] AssemblyProduct = "FsAutoComplete.Suave"
    let [<Literal>] AssemblyDescription = "A Suave web server for interfacing with FSharp.Compiler.Service over a HTTP."
    let [<Literal>] AssemblyVersion = "0.30.2"
    let [<Literal>] AssemblyFileVersion = "0.30.2"
