// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsAutoComplete")>]
[<assembly: AssemblyProductAttribute("FsAutoComplete")>]
[<assembly: AssemblyDescriptionAttribute("A command line tool for interfacing with FSharp.Compiler.Service over a pipe.")>]
[<assembly: AssemblyVersionAttribute("0.34.0")>]
[<assembly: AssemblyFileVersionAttribute("0.34.0")>]
[<assembly: AssemblyMetadataAttribute("githash","a08608e74ab409a7852deffb566b9ee5ac72e78b")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsAutoComplete"
    let [<Literal>] AssemblyProduct = "FsAutoComplete"
    let [<Literal>] AssemblyDescription = "A command line tool for interfacing with FSharp.Compiler.Service over a pipe."
    let [<Literal>] AssemblyVersion = "0.34.0"
    let [<Literal>] AssemblyFileVersion = "0.34.0"
    let [<Literal>] AssemblyMetadata_githash = "a08608e74ab409a7852deffb566b9ee5ac72e78b"
