// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsAutoComplete")>]
[<assembly: AssemblyProductAttribute("FsAutoComplete")>]
[<assembly: AssemblyDescriptionAttribute("A command line tool for interfacing with FSharp.Compiler.Service over a pipe.")>]
[<assembly: AssemblyVersionAttribute("0.40.0")>]
[<assembly: AssemblyFileVersionAttribute("0.40.0")>]
[<assembly: AssemblyMetadataAttribute("githash","4c2ec2ca97a619bf3ffd32fbcf081191662afbdb")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsAutoComplete"
    let [<Literal>] AssemblyProduct = "FsAutoComplete"
    let [<Literal>] AssemblyDescription = "A command line tool for interfacing with FSharp.Compiler.Service over a pipe."
    let [<Literal>] AssemblyVersion = "0.40.0"
    let [<Literal>] AssemblyFileVersion = "0.40.0"
    let [<Literal>] AssemblyMetadata_githash = "4c2ec2ca97a619bf3ffd32fbcf081191662afbdb"
