name: Copilot Setup Steps

# This workflow is designed to be used by GitHub Copilot coding agents
# to set up the environment needed to work with the FsAutoComplete repository

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Announce .NET version
      run: dotnet --info

    - name: Restore tools
      run: dotnet tool restore

    - name: Restore packages
      run: dotnet restore

    - name: Build solution
      run: dotnet build -c Release --no-restore

    - name: Verify Fantomas formatting
      run: dotnet fantomas --check build.fsx src
      env:
        DOTNET_ROLL_FORWARD: LatestMajor
        DOTNET_ROLL_FORWARD_TO_PRERELEASE: 1

    - name: Run quick tests
      run: dotnet test -c Release -f net8.0 --no-restore --no-build --logger "console;verbosity=minimal" -- Expecto.fail-on-focused-tests=true
      working-directory: test/FsAutoComplete.Tests.Lsp
      timeout-minutes: 5
      continue-on-error: true # Don't fail the setup if tests fail

    - name: Setup completed
      run: |
        echo "✅ Copilot setup completed successfully!"
        echo "📦 Dependencies restored"
        echo "🔨 Build verified"
        echo "📝 Code formatting checked"
        echo "🧪 Basic tests run"
        echo ""
        echo "The environment is ready for Copilot to work with FsAutoComplete."
